name: Autorelease

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      new_version:
        description: "New tag version"
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
  schedule:
    - cron: "0 2 * * 6"

jobs:
  autorelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
      pull-requests: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: Setup git config
        run: |
          git config user.name actions-bot
          git config user.email actions-bot@users.noreply.github.com

      - name: Install mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3

      - name: Install dependencies
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: Check for changes and create PR
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8
        id: pr_create
        with:
          commit-message: "chore: update generated code"
          branch: updater-bot
          delete-branch: true
          title: "chore: update generated code"
          body: |
            Automated changes by `mise run codegen`.

      - name: Stop if PR created
        if: steps.pr_create.outputs.pull-request-number != ''
        run: |
          echo "Changes detected and PR created. Stopping workflow."
          exit 1

      - name: CI
        run: mise run ci

      - name: Determine Release Version
        if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.new_version != '')
        id: release_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
             NO_TAG=1 ./make_release "${{ github.event.inputs.new_version }}"
             echo "version=$(cat ./bumpkin/VERSION)" >> $GITHUB_OUTPUT
          else
             echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: steps.release_version.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.release_version.outputs.version }}
          TITLE: Release ${{ steps.release_version.outputs.version }}
        run: |
          gh release create "$TAG" \
            --title "$TITLE" \
            --generate-notes \
            --notes-start-tag $(gh release list --limit 1 --json tagName -q .[].tagName)

      - name: Login to registry
        if: steps.release_version.outputs.version != ''
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ github.token }}

      - name: Build and publish container
        if: steps.release_version.outputs.version != ''
        env:
          TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          VERSION: ${{ steps.release_version.outputs.version }}
        run: |
          docker build -t "$TAG:$VERSION" . -f Containerfile
          docker tag "$TAG:$VERSION" "$TAG:latest"
          docker push "$TAG:$VERSION"
          docker push "$TAG:latest"

      - name: Build and publish to PyPI
        if: steps.release_version.outputs.version != ''
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv build
          uvx twine upload dist/*
